language: python
python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2
  - 3.3
  - pypy
script:
  - python -m blackskirt.lib.ops
  - python -m blackskirt
install:
  - python setup.py install
notifications:
  email: false
